name: my_mesl7y_app_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  crypto: ^3.0.7
  serverpod: 2.9.2
  serverpod_swagger: ^0.1.7

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.2

# ---------------- Swagger Configuration ----------------
open_api:
  enabled: true
  path: /swagger/index.html   # ده الرابط اللي هتدخل عليه من المتصفح